### ISSUE TITLE
research and create a page that can generate code

### ISSUE THREAD

**Issue by saitodisse** [nextjs-opinionated/nextjs-opinionated#35]
- [x] ~~search alternatives like https://www.hygen.io/. Search for a tool that can generate code inside existing files.~~ **hygen was made to be a command line tool.**
- [x] create a form to input a title and generates a string with typescript tsx
- [-] output must be highlighted
- [-] create tabs for each file that will be generated
- [-] limit use of this form to localhost only
- [x] button create files will generate files in the project

## Examples
- [x] Simple component

**Comment by thaila-curty-linx** [comment]
the hygen.io can generate code inside an existing file
